# Welcome to Jekyll!
# Jekyll workshop template
# based on minima theme https://github.com/jekyll/minima

# Site settings

title: Hello Arduino!
description: > 
  Learn about the Arduino electronics platform by making lights blink and buzzers buzz! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evanwill.github.io/arduinoIntro" # the base hostname & protocol for your site

google_analytics: UA-74844011-1

# Build settings
markdown: kramdown
