# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Site settings

title: Hello Arduino!
description: > 
  Learn about the Arduino electronics platform by making lights blink and buzzers buzz! 
keywords: "arduino workshop, code intro, light theremin"

url: "https://evanwill.github.io/arduinoIntro" # the base hostname & protocol for your site

google_analytics: UA-74844011-1

# author settings for cc-by
author: evan will
github_username: evanwill
pub_year: 2017
repo: "https://github.com/evanwill/hello-arduino"

# Build settings
markdown: kramdown
